Repository sillsdev/silnlp, pull requests merged in 2023-11, with the labels that each got.

#223 add support for copying paratext projects from S3 bucket
  silnlp/common/environment.py
  silnlp/common/extract_corpora.py
Labels: enhancement

#227 Download paratext projects from S3 bucket to cache
  silnlp/common/translate_google.py
  silnlp/nmt/translate.py
Labels: bug

#232 update sil-machine
  poetry.lock
  pyproject.toml
Labels: bug

#237 Report all errors when translating.
  silnlp/common/translator.py
  silnlp/nmt/translate.py
  silnlp/sfm/usfm.py
Labels: enhancement, good first issue, pipeline 6: infer

#235 add functionality for detecting versification when extracting corpora
  silnlp/common/extract_corpora.py
  silnlp/common/paratext.py
Labels: enhancement
