Repository sillsdev/silnlp, pull requests merged in 2024-09, with the labels that each got.

#503 Issue 333: Fixed bug with dupe key terms during preprocessing
  silnlp/nmt/config.py
  silnlp/nmt/hugging_face_config.py
  silnlp/nmt/open_nmt_config.py
Labels: pipeline 3: preprocess

#524 add conda environment.yml for non-python-package dependencies
  environment.yml
Labels: enhancement, mlops

#528 Update README.md with conda instructions
  README.md
Labels: documentation

#539 keep with statement syntax compatible with python 3.8
  silnlp/nmt/hugging_face_config.py
  silnlp/nmt/open_nmt_config.py
Labels: bug
